In [18]:
### homework 1 2017

### read in data
data = 
[1 2.0;
2 2.1;
3 3.4;
4 3.3;
5 5.2]

x = data[:,1]
y = data[:,2]
[y x]


5×2 Array{Float64,2}:
 2.0  1.0
 2.1  2.0
 3.4  3.0
 3.3  4.0
 5.2  5.0

In [20]:
 n = length(y)
 ones(n)
  X = [ones(n) x]
  b = X \ y
  resids = y - X*b
b

2-element Array{Float64,1}:
 0.92
 0.76

In [24]:
using Plots
plot(x,y, st=:scatter, label = "actual",legend = :topleft)
yhat = b[1] .+ b[2].*x
plot!(x,yhat, st=:scatter, color = :green, label = "predicted")

<?xml version="1.0" encoding="utf-8"?>
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 1 
 
 
 2 
 
 
 3 
 
 
 4 
 
 
 5 
 
 
 2 
 
 
 3 
 
 
 4 
 
 
 5 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 actual 
 
 
 
 
 predicted

In [68]:
# regression function
function linreg(y,x)
  # add intercept
  n = length(y)
  X = [ones(n) x]
  b = X \ y
  resids = y - X*b
    
  s2 = sum(resids.^2)/n
  covb = s2*inv(X'X)  
  seb = diag(covb)
  
  println("coeffs = ",round.(b,3))
  println(" s.e's = ",round.(seb,3))
  println("s^2 (eqn. variance) = ",round(s2,6))

  # compute R^2
  tss = sum((y .- mean(y)).^2)
  R2 = 1 - s2*n/tss
  println("Rsquared = ",round(R2,3))
  s = sqrt(s2)
  return b, seb, s, R2
end

b, s, R2 = linreg(y,x)

coeffs = [0.92, 0.76]
 s.e's = [0.203, 0.018]
s^2 (eqn. variance) = 0.1848
Rsquared = 0.862


([0.92, 0.76], [0.20328, 0.01848], 0.4298837052040938, 0.8620895522388058)

In [33]:
sum((y .- mean(y)).^2)

6.7

In [35]:
seb = (s^2)*inv(X'X)

2×2 Array{Float64,2}:
  0.20328  -0.05544
 -0.05544   0.01848

In [50]:
ses = round.(diag(seb),3)

2-element Array{Float64,1}:
 0.203
 0.018

In [42]:
string(seb)

"[0.20328 -0.05544; -0.05544 0.01848]"

In [46]:
ses = string(diag(seb))
println(ses[1:12])
print(round.(rand(3),3))

[0.20328, 0.
[0.003, 0.31, 0.599]

In [61]:
ses = round.(diag(seb),3)
b[1] = 0.921
nam1 = "coeffs" 
nam2 = "s.e's"
nams = [nam1; nam2]
[nams b ses]

2×3 Array{Any,2}:
 "coeffs"  0.921  0.203
 "s.e's"   0.76   0.018

In [59]:
nams = ["coeffs" "ses"]

1×2 Array{String,2}:
 "coeffs"  "ses"

In [1]:
using Distributions
function marg_post_mu(m,s2,n; M = 10000)
  v = n - 1
  vs2 = v*s2
  # need to either evaluate pdf of t, or
  # draw from t and plot pseudo-sample
  ts = m + sqrt(s2)*rand(TDist(v),M)
  return ts
end


marg_post_mu (generic function with 1 method)

In [27]:
# generate fake data!
n = 100
s = 0.5
x = rand(Normal(),n)
y = rand(Normal(1,s),n)
using Plots
plot(x,y,st=:scatter)

<?xml version="1.0" encoding="utf-8"?>
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 -2 
 
 
 -1 
 
 
 0 
 
 
 1 
 
 
 2 
 
 
 -0.5 
 
 
 0.0 
 
 
 0.5 
 
 
 1.0 
 
 
 1.5 
 
 
 2.0 
 
 
 2.5 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 y1

### Plotting t-distribution using analytic formula vs. draws from t

In [20]:
using Distributions, Plots, Interact
gr()
b = -5.0:0.1:5.0
pbt = pdf(TDist(8),b)
pbn = pdf(Normal(0,1),b)
gui()
@manipulate for v=3:100
    plot(b,pbn, linecolor=:red,label="Normal",linestyle=:dash)
    plot!(b,pdf(TDist(v),b),linecolor=:blue,label="Student-t")
end
#plot!(b,pbn, linecolor=:red,label="Normal",linestyle=:dash)

Interact.Options{:SelectionSlider,Int64}(23: "input-7" = 51 Int64 , "v", 51, "51", Interact.OptionDict(DataStructures.OrderedDict("3"=>3,"4"=>4,"5"=>5,"6"=>6,"7"=>7,"8"=>8,"9"=>9,"10"=>10,"11"=>11,"12"=>12…), Dict(68=>"68",89=>"89",11=>"11",39=>"39",46=>"46",85=>"85",25=>"25",55=>"55",42=>"42",29=>"29"…)), Any[], Any[], true, "horizontal")

<?xml version="1.0" encoding="utf-8"?>
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 -5.0 
 
 
 -2.5 
 
 
 0.0 
 
 
 2.5 
 
 
 5.0 
 
 
 0.05 
 
 
 0.10 
 
 
 0.15 
 
 
 0.20 
 
 
 0.25 
 
 
 0.30 
 
 
 0.35 
 
<polyline clip-path="url(#clip02)" style="stroke:#ff0000; stroke-width:1; stroke-opacity:1; fill:none" stroke-dasharray="8, 5" points="
 38.8117,375.813 44.2268,375.813 49.6418,375.811 55.0568,375.809 60.4719,375.806 65.8869,375.8 71.3019,375.792 76.717,375.78 82.132,375.761 87.547,375.733 
 92.9621,375.693 98.3771,375.634 103.792,375.548 109.207,375.427 114.622,375.256 120.037,375.019 125.452,374.691 130.867,374.243 136.282,373.64 141.697,372.834 
 147.112,371.771 152.527,370.384 157.942,368.593 163.357,366.307 168.773,363.421 174.188,359.822 179.603,355.382 185.018,349.969 190.433,343.447 195.848,335.683 
 201.263,326.552 206.678,315.945 212.093,303.779 217.508,290.002 222.923,274.608 228.338,257.64 233.753,239.2 239.168,219.454 244.583,198.635 249.998,177.042 
 255.413,155.035 260.828,133.033 266.243,111.494 271.658,90.9074 277.073,71.7733 282.488,54.5826 287.903,39.797 293.318,27.8281 298.733,19.0188 304.148,13.6265 
 309.563,11.811 314.978,13.6265 320.393,19.0188 325.808,27.8281 331.223,39.797 336.639,54.5826 342.054,71.7733 347.469,90.9074 352.884,111.494 358.299,133.033 
 363.714,155.035 369.129,177.042 374.544,198.635 379.959,219.454 385.374,239.2 390.789,257.64 396.204,274.608 401.619,290.002 407.034,303.779 412.449,315.945 
 417.864,326.552 423.279,335.683 428.694,343.447 434.109,349.969 439.524,355.382 444.939,359.822 450.354,363.421 455.769,366.307 461.184,368.593 466.599,370.384 
 472.014,371.771 477.429,372.834 482.844,373.64 488.259,374.243 493.674,374.691 499.089,375.019 504.505,375.256 509.92,375.427 515.335,375.548 520.75,375.634 
 526.165,375.693 531.58,375.733 536.995,375.761 542.41,375.78 547.825,375.792 553.24,375.8 558.655,375.806 564.07,375.809 569.485,375.811 574.9,375.813 
 580.315,375.813 
 "/>
<polyline clip-path="url(#clip02)" style="stroke:#0000ff; stroke-width:1; stroke-opacity:1; fill:none" points="
 38.8117,375.803 44.2268,375.799 49.6418,375.792 55.0568,375.784 60.4719,375.771 65.8869,375.754 71.3019,375.731 76.717,375.698 82.132,375.655 87.547,375.595 
 92.9621,375.514 98.3771,375.406 103.792,375.26 109.207,375.067 114.622,374.81 120.037,374.471 125.452,374.028 130.867,373.451 136.282,372.704 141.697,371.744 
 147.112,370.52 152.527,368.969 157.942,367.018 163.357,364.585 168.773,361.575 174.188,357.882 179.603,353.391 185.018,347.98 190.433,341.521 195.848,333.886 
 201.263,324.955 206.678,314.619 212.093,302.787 217.508,289.4 222.923,274.436 228.338,257.921 233.753,239.935 239.168,220.623 244.583,200.196 249.998,178.933 
 255.413,157.182 260.828,135.352 266.243,113.9 271.658,93.3226 277.073,74.1315 282.488,56.8365 287.903,41.9214 293.318,29.8211 298.733,20.8998 304.148,15.4326 
 309.563,13.5909 314.978,15.4326 320.393,20.8998 325.808,29.8211 331.223,41.9214 336.639,56.8365 342.054,74.1315 347.469,93.3226 352.884,113.9 358.299,135.352 
 363.714,157.182 369.129,178.933 374.544,200.196 379.959,220.623 385.374,239.935 390.789,257.921 396.204,274.436 401.619,289.4 407.034,302.787 412.449,314.619 
 417.864,324.955 423.279,333.886 428.694,341.521 434.109,347.98 439.524,353.391 444.939,357.882 450.354,361.575 455.769,364.585 461.184,367.018 466.599,368.969 
 472.014,370.52 477.429,371.744 482.844,372.704 488.259,373.451 493.674,374.028 499.089,374.471 504.505,374.81 509.92,375.067 515.335,375.26 520.75,375.406 
 526.165,375.514 531.58,375.595 536.995,375.655 542.41,375.698 547.825,375.731 553.24,375.754 558.655,375.771 564.07,375.784 569.485,375.792 574.9,375.799 
 580.315,375.803 
 "/>
 
 
 
 
 Normal 
 
 
 
 Student-t

  likely near C:\Users\millsjf.UCCOB\AppData\Local\JuliaPro-0.6\pkgs-0.6.0.1\v0.6\IJulia\src\kernel.jl:31
  likely near C:\Users\millsjf.UCCOB\AppData\Local\JuliaPro-0.6\pkgs-0.6.0.1\v0.6\IJulia\src\kernel.jl:31
  likely near C:\Users\millsjf.UCCOB\AppData\Local\JuliaPro-0.6\pkgs-0.6.0.1\v0.6\IJulia\src\kernel.jl:31
  likely near C:\Users\millsjf.UCCOB\AppData\Local\JuliaPro-0.6\pkgs-0.6.0.1\v0.6\IJulia\src\kernel.jl:31


In [21]:
using StatPlots
bdraws = rand(Normal(0,1),100000)
plot!(bdraws,st=:density,linecolor=:red,label="Normal draws")
bdrawst = rand(TDist(100),100000)
plot!(bdraws,st=:density,linecolor=:orange,label="t draws")


<?xml version="1.0" encoding="utf-8"?>
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 -5.0 
 
 
 -2.5 
 
 
 0.0 
 
 
 2.5 
 
 
 5.0 
 
 
 0.05 
 
 
 0.10 
 
 
 0.15 
 
 
 0.20 
 
 
 0.25 
 
 
 0.30 
 
 
 0.35 
 
<polyline clip-path="url(#clip02)" style="stroke:#ff0000; stroke-width:1; stroke-opacity:1; fill:none" stroke-dasharray="8, 5" points="
 38.8117,375.812 44.2268,375.811 49.6418,375.81 55.0568,375.808 60.4719,375.804 65.8869,375.799 71.3019,375.791 76.717,375.778 82.132,375.76 87.547,375.732 
 92.9621,375.691 98.3771,375.632 103.792,375.547 109.207,375.426 114.622,375.255 120.037,375.017 125.452,374.689 130.867,374.242 136.282,373.638 141.697,372.833 
 147.112,371.77 152.527,370.382 157.942,368.591 163.357,366.305 168.773,363.42 174.188,359.82 179.603,355.38 185.018,349.967 190.433,343.446 195.848,335.682 
 201.263,326.551 206.678,315.944 212.093,303.778 217.508,290.001 222.923,274.607 228.338,257.639 233.753,239.199 239.168,219.454 244.583,198.634 249.998,177.041 
 255.413,155.035 260.828,133.032 266.243,111.493 271.658,90.9071 277.073,71.7731 282.488,54.5824 287.903,39.7969 293.318,27.828 298.733,19.0188 304.148,13.6265 
 309.563,11.811 314.978,13.6265 320.393,19.0188 325.808,27.828 331.223,39.7969 336.639,54.5824 342.054,71.7731 347.469,90.9071 352.884,111.493 358.299,133.032 
 363.714,155.035 369.129,177.041 374.544,198.634 379.959,219.454 385.374,239.199 390.789,257.639 396.204,274.607 401.619,290.001 407.034,303.778 412.449,315.944 
 417.864,326.551 423.279,335.682 428.694,343.446 434.109,349.967 439.524,355.38 444.939,359.82 450.354,363.42 455.769,366.305 461.184,368.591 466.599,370.382 
 472.014,371.77 477.429,372.833 482.844,373.638 488.259,374.242 493.674,374.689 499.089,375.017 504.505,375.255 509.92,375.426 515.335,375.547 520.75,375.632 
 526.165,375.691 531.58,375.732 536.995,375.76 542.41,375.778 547.825,375.791 553.24,375.799 558.655,375.804 564.07,375.808 569.485,375.81 574.9,375.811 
 580.315,375.812 
 "/>
<polyline clip-path="url(#clip02)" style="stroke:#0000ff; stroke-width:1; stroke-opacity:1; fill:none" points="
 38.8117,375.802 44.2268,375.798 49.6418,375.791 55.0568,375.782 60.4719,375.77 65.8869,375.753 71.3019,375.729 76.717,375.697 82.132,375.653 87.547,375.594 
 92.9621,375.513 98.3771,375.404 103.792,375.259 109.207,375.065 114.622,374.808 120.037,374.47 125.452,374.027 130.867,373.449 136.282,372.703 141.697,371.743 
 147.112,370.518 152.527,368.967 157.942,367.017 163.357,364.584 168.773,361.574 174.188,357.881 179.603,353.39 185.018,347.979 190.433,341.519 195.848,333.885 
 201.263,324.954 206.678,314.617 212.093,302.786 217.508,289.399 222.923,274.435 228.338,257.92 233.753,239.934 239.168,220.622 244.583,200.195 249.998,178.932 
 255.413,157.182 260.828,135.351 266.243,113.9 271.658,93.3223 277.073,74.1312 282.488,56.8364 287.903,41.9213 293.318,29.821 298.733,20.8997 304.148,15.4326 
 309.563,13.5909 314.978,15.4326 320.393,20.8997 325.808,29.821 331.223,41.9213 336.639,56.8364 342.054,74.1312 347.469,93.3223 352.884,113.9 358.299,135.351 
 363.714,157.182 369.129,178.932 374.544,200.195 379.959,220.622 385.374,239.934 390.789,257.92 396.204,274.435 401.619,289.399 407.034,302.786 412.449,314.617 
 417.864,324.954 423.279,333.885 428.694,341.519 434.109,347.979 439.524,353.39 444.939,357.881 450.354,361.574 455.769,364.584 461.184,367.017 466.599,368.967 
 472.014,370.518 477.429,371.743 482.844,372.703 488.259,373.449 493.674,374.027 499.089,374.47 504.505,374.808 509.92,375.065 515.335,375.259 520.75,375.404 
 526.165,375.513 531.58,375.594 536.995,375.653 542.41,375.697 547.825,375.729 553.24,375.753 558.655,375.77 564.07,375.782 569.485,375.791 574.9,375.798 
 580.315,375.802 
 "/>
<polyline clip-path="url(#clip02)" style="stroke:#ff0000; stroke-width:1; stroke-opacity:1; fill:none" points="
 65.4007,375.813 67.8662,375.813 70.3316,375.813 72.7971,375.811 75.2626,375.807 77.7281,375.798 80.1936,375.782 82.6591,375.761 85.1245,375.738 87.5

In [36]:
# now how to plot pdf analytically for Student-t when noncentral
# Using a normal distribution
b1 = 2.025
seb1 = 0.676
pbn = pdf(Normal(b1,seb1),b)
plot(b,pbn,linecolor=:blue,label="Normal analytical")

bdraws = rand(Normal(b1,seb1),2000000)
plot!(bdraws,st=:density,linecolor=:red,label="Normal draws")
bdrawst = rand(TDist(100),2000000).*seb1 + b1
plot!(bdrawst,st=:density,linecolor=:orange,label="t draws")

<?xml version="1.0" encoding="utf-8"?>
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 -4 
 
 
 -2 
 
 
 0 
 
 
 2 
 
 
 4 
 
 
 0.1 
 
 
 0.2 
 
 
 0.3 
 
 
 0.4 
 
 
 0.5 
 
<polyline clip-path="url(#clip02)" style="stroke:#0000ff; stroke-width:1; stroke-opacity:1; fill:none" points="
 32.2221,375.813 37.3597,375.813 42.4973,375.813 47.6349,375.813 52.7725,375.813 57.91,375.813 63.0476,375.813 68.1852,375.813 73.3228,375.813 78.4604,375.813 
 83.598,375.813 88.7356,375.813 93.8732,375.813 99.0107,375.813 104.148,375.813 109.286,375.813 114.424,375.813 119.561,375.813 124.699,375.813 129.836,375.813 
 134.974,375.813 140.111,375.813 145.249,375.813 150.387,375.813 155.524,375.813 160.662,375.813 165.799,375.813 170.937,375.813 176.075,375.813 181.212,375.813 
 186.35,375.813 191.487,375.813 196.625,375.813 201.762,375.813 206.9,375.813 212.038,375.813 217.175,375.812 222.313,375.811 227.45,375.809 232.588,375.805 
 237.726,375.797 242.863,375.782 248.001,375.755 253.138,375.706 258.276,375.62 263.414,375.474 268.551,375.229 273.689,374.831 278.826,374.198 283.964,373.213 
 289.101,371.718 294.239,369.504 299.377,366.304 304.514,361.79 309.652,355.581 314.789,347.255 319.927,336.376 325.065,322.531 330.202,305.384 335.34,284.733 
 340.477,260.577 345.615,233.171 350.753,203.068 355.89,171.141 361.028,138.562 366.165,106.749 371.303,77.2764 376.44,51.7449 381.578,31.6443 386.716,18.2086 
 391.853,12.2911 396.991,14.2744 402.128,24.0298 407.266,40.931 412.404,63.9206 417.541,91.6194 422.679,122.464 427.816,154.849 432.954,187.266 438.092,218.409 
 443.229,247.253 448.367,273.084 453.504,295.502 458.642,314.387 463.779,329.848 468.917,342.162 474.055,351.71 479.192,358.923 484.33,364.234 489.467,368.046 
 494.605,370.716 499.743,372.541 504.88,373.758 510.018,374.55 515.155,375.054 520.293,375.367 525.431,375.556 530.568,375.669 535.706,375.734 540.843,375.77 
 545.981,375.791 
 "/>
<polyline clip-path="url(#clip02)" style="stroke:#ff0000; stroke-width:1; stroke-opacity:1; fill:none" points="
 214.043,375.813 215.791,375.813 217.539,375.813 219.287,375.81 221.035,375.807 222.784,375.808 224.532,375.811 226.28,375.812 228.028,375.809 229.776,375.805 
 231.524,375.8 233.272,375.79 235.021,375.783 236.769,375.787 238.517,375.792 240.265,375.792 242.013,375.791 243.761,375.783 245.51,375.765 247.258,375.752 
 249.006,375.743 250.754,375.723 252.502,375.7 254.25,375.681 255.999,375.657 257.747,375.61 259.495,375.566 261.243,375.521 262.991,375.461 264.739,375.402 
 266.487,375.333 268.236,375.255 269.984,375.15 271.732,374.985 273.48,374.769 275.228,374.565 276.976,374.441 278.725,374.29 280.473,373.965 282.221,373.536 
 283.969,373.13 285.717,372.745 287.465,372.274 289.213,371.667 290.962,370.965 292.71,370.151 294.458,369.24 296.206,368.325 297.954,367.356 299.702,366.139 
 301.451,364.539 303.199,362.692 304.947,360.805 306.695,358.94 308.443,357.057 310.191,354.82 311.94,352.206 313.688,349.384 315.436,346.149 317.184,342.478 
 318.932,338.517 320.68,334.361 322.428,329.892 324.177,324.882 325.925,319.774 327.673,314.53 329.421,308.659 331.169,302.125 332.917,294.965 334.666,287.253 
 336.414,279.345 338.162,271.539 339.91,263.607 341.658,255.198 343.406,246.092 345.155,236.374 346.903,226.565 348.651,216.565 350.399,205.797 352.147,194.704 
 353.895,183.583 355.643,172.172 357.392,160.975 359.14,150.513 360.888,140.215 362.636,129.199 364.384,117.966 366.132,107.297 367.881,97.2422 369.629,87.5367 
 371.377,77.6169 373.125,67.742 374.873,58.2671 376.621,49.7303 378.37,42.55 380.118,36.01 381.866,30.4423 383.614,25.4969 385.362,20.7707 387.11,16.9746 
 388.858,14.2093 390.607,12.3382 392.355,11.811 394.103,12.8728 395.851,14.6059 397.599,16.431 399.347,18.3694 401.096,21.1478 402.844,25.4198 404.592,31.0568 
 406.34,37.904 408.088,45.6065 409.836,53.1931 411.584,60.0218 413.333,67.3469 415.081,77.0511 416.829,88.6396 418.577,99.8503 420.325,109.753 422.073,119.566 
 423.822,130.201 425.57,141.29

In [19]:
#pbt = zeros(length(b))
#for i = 1:length(b)
#    tb = (b[i] - b1)/seb1
#    pbt[i] = pdf(TDist(98),tb)
#end

### WHY the need to arbitrarily scale up?
#plot!(b,pbt,linecolor=:purple,label="analytical t scaled up")

<?xml version="1.0" encoding="utf-8"?>
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 -4 
 
 
 -2 
 
 
 0 
 
 
 2 
 
 
 4 
 
 
 0.1 
 
 
 0.2 
 
 
 0.3 
 
 
 0.4 
 
 
 0.5 
 
<polyline clip-path="url(#clip02)" style="stroke:#0000ff; stroke-width:1; stroke-opacity:1; fill:none" points="
 32.2221,375.813 37.5238,375.813 42.8255,375.813 48.1272,375.813 53.4288,375.813 58.7305,375.813 64.0322,375.813 69.3339,375.813 74.6356,375.813 79.9373,375.813 
 85.2389,375.813 90.5406,375.813 95.8423,375.813 101.144,375.813 106.446,375.813 111.747,375.813 117.049,375.813 122.351,375.813 127.652,375.813 132.954,375.813 
 138.256,375.813 143.557,375.813 148.859,375.813 154.161,375.813 159.463,375.813 164.764,375.813 170.066,375.813 175.368,375.813 180.669,375.813 185.971,375.813 
 191.273,375.813 196.574,375.813 201.876,375.813 207.178,375.813 212.479,375.813 217.781,375.813 223.083,375.812 228.384,375.811 233.686,375.809 238.988,375.805 
 244.289,375.797 249.591,375.782 254.893,375.755 260.195,375.706 265.496,375.62 270.798,375.473 276.1,375.229 281.401,374.83 286.703,374.196 292.005,373.209 
 297.306,371.713 302.608,369.496 307.91,366.291 313.211,361.772 318.513,355.555 323.815,347.219 329.116,336.325 334.418,322.463 339.72,305.294 345.021,284.617 
 350.323,260.43 355.625,232.988 360.927,202.847 366.228,170.879 371.53,138.258 376.832,106.405 382.133,76.8944 387.435,51.3302 392.737,31.2039 398.038,17.751 
 403.34,11.8259 408.642,13.8118 413.943,23.5797 419.245,40.5025 424.547,63.5214 429.848,91.2558 435.15,122.139 440.452,154.566 445.753,187.024 451.055,218.208 
 456.357,247.089 461.659,272.953 466.96,295.399 472.262,314.308 477.564,329.789 482.865,342.119 488.167,351.679 493.469,358.901 498.77,364.219 504.072,368.036 
 509.374,370.71 514.675,372.537 519.977,373.755 525.279,374.549 530.58,375.053 535.882,375.366 541.184,375.556 546.485,375.669 551.787,375.734 557.089,375.77 
 562.391,375.791 
 "/>
<polyline clip-path="url(#clip02)" style="stroke:#ff0000; stroke-width:1; stroke-opacity:1; fill:none" points="
 241.542,375.813 243.22,375.813 244.898,375.813 246.575,375.811 248.253,375.805 249.931,375.793 251.609,375.772 253.287,375.741 254.965,375.707 256.643,375.675 
 258.321,375.654 259.999,375.645 261.676,375.64 263.354,375.62 265.032,375.578 266.71,375.519 268.388,375.455 270.066,375.392 271.744,375.334 273.422,375.286 
 275.099,375.251 276.777,375.215 278.455,375.156 280.133,375.051 281.811,374.898 283.489,374.7 285.167,374.456 286.845,374.168 288.523,373.852 290.2,373.528 
 291.878,373.182 293.556,372.767 295.234,372.249 296.912,371.635 298.59,370.961 300.268,370.254 301.946,369.532 303.624,368.785 305.301,367.965 306.979,366.997 
 308.657,365.858 310.335,364.607 312.013,363.3 313.691,361.888 315.369,360.224 317.047,358.199 318.724,355.814 320.402,353.146 322.08,350.234 323.758,347.026 
 325.436,343.434 327.114,339.453 328.792,335.166 330.47,330.658 332.148,325.993 333.825,321.28 335.503,316.619 337.181,311.943 338.859,306.976 340.537,301.396 
 342.215,295.077 343.893,288.17 345.571,280.901 347.248,273.349 348.926,265.545 350.604,257.603 352.282,249.551 353.96,241.203 355.638,232.42 357.316,223.348 
 358.994,214.221 360.672,205.042 362.349,195.563 364.027,185.499 365.705,174.842 367.383,163.995 369.061,153.474 370.739,143.398 372.417,133.371 374.095,122.936 
 375.772,112.175 377.45,101.788 379.128,92.4161 380.806,83.9509 382.484,75.7192 384.162,67.2066 385.84,58.3848 387.518,49.561 389.196,41.2332 390.873,34.0078 
 392.551,28.3825 394.229,24.4576 395.907,21.8516 397.585,19.9827 399.263,18.4327 400.941,16.9737 402.619,15.4565 404.297,14.0089 405.974,13.1997 407.652,13.6396 
 409.33,15.4984 411.008,18.5937 412.686,22.6919 414.364,27.4867 416.042,32.5151 417.72,37.4082 419.397,42.2735 421.075,47.7056 422.753,54.3141 424.431,62.2076 
 426.109,70.9966 427.787,80.3474 429.465,90.3202 431.143,100.919 432.821,111.593 434.498,121.614 436.176,130.811 437.854,139.648 439.532,148.724 441.21,158.357 
 442.888,168.473 

In [16]:
## using the formula:
function student_t(x,mu,sig,v)
    lc = lgamma((v+1)/2) - 0.5*log(pi*v*sig^2) - lgamma(v/2)
    k = (1 + ((x - mu)^2)/(v*sig^2))^(-(v+1)/2)
    return exp(lc)*k
end
# THIS WORKS - formula gives correct scale, but
# the function TDist in Distributions does not
# seem to - not sure why.

student_t (generic function with 1 method)

In [37]:

pstb = zeros(length(b))
for i in 1:length(b)
    pstb[i] = student_t(b[i],b1,seb1,98)
end
plot!(b,pstb,linecolor=:orange,label="analytical t formula",legend=:topleft)

<?xml version="1.0" encoding="utf-8"?>
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 -4 
 
 
 -2 
 
 
 0 
 
 
 2 
 
 
 4 
 
 
 0.1 
 
 
 0.2 
 
 
 0.3 
 
 
 0.4 
 
 
 0.5 
 
<polyline clip-path="url(#clip02)" style="stroke:#0000ff; stroke-width:1; stroke-opacity:1; fill:none" points="
 32.2221,375.813 37.3597,375.813 42.4973,375.813 47.6349,375.813 52.7725,375.813 57.91,375.813 63.0476,375.813 68.1852,375.813 73.3228,375.813 78.4604,375.813 
 83.598,375.813 88.7356,375.813 93.8732,375.813 99.0107,375.813 104.148,375.813 109.286,375.813 114.424,375.813 119.561,375.813 124.699,375.813 129.836,375.813 
 134.974,375.813 140.111,375.813 145.249,375.813 150.387,375.813 155.524,375.813 160.662,375.813 165.799,375.813 170.937,375.813 176.075,375.813 181.212,375.813 
 186.35,375.813 191.487,375.813 196.625,375.813 201.762,375.813 206.9,375.813 212.038,375.813 217.175,375.812 222.313,375.811 227.45,375.809 232.588,375.805 
 237.726,375.797 242.863,375.782 248.001,375.755 253.138,375.706 258.276,375.62 263.414,375.474 268.551,375.229 273.689,374.831 278.826,374.198 283.964,373.213 
 289.101,371.718 294.239,369.504 299.377,366.304 304.514,361.79 309.652,355.581 314.789,347.255 319.927,336.376 325.065,322.531 330.202,305.384 335.34,284.733 
 340.477,260.577 345.615,233.171 350.753,203.068 355.89,171.141 361.028,138.562 366.165,106.749 371.303,77.2764 376.44,51.7449 381.578,31.6443 386.716,18.2086 
 391.853,12.2911 396.991,14.2744 402.128,24.0298 407.266,40.931 412.404,63.9206 417.541,91.6194 422.679,122.464 427.816,154.849 432.954,187.266 438.092,218.409 
 443.229,247.253 448.367,273.084 453.504,295.502 458.642,314.387 463.779,329.848 468.917,342.162 474.055,351.71 479.192,358.923 484.33,364.234 489.467,368.046 
 494.605,370.716 499.743,372.541 504.88,373.758 510.018,374.55 515.155,375.054 520.293,375.367 525.431,375.556 530.568,375.669 535.706,375.734 540.843,375.77 
 545.981,375.791 
 "/>
<polyline clip-path="url(#clip02)" style="stroke:#ff0000; stroke-width:1; stroke-opacity:1; fill:none" points="
 214.043,375.813 215.791,375.813 217.539,375.813 219.287,375.81 221.035,375.807 222.784,375.808 224.532,375.811 226.28,375.812 228.028,375.809 229.776,375.805 
 231.524,375.8 233.272,375.79 235.021,375.783 236.769,375.787 238.517,375.792 240.265,375.792 242.013,375.791 243.761,375.783 245.51,375.765 247.258,375.752 
 249.006,375.743 250.754,375.723 252.502,375.7 254.25,375.681 255.999,375.657 257.747,375.61 259.495,375.566 261.243,375.521 262.991,375.461 264.739,375.402 
 266.487,375.333 268.236,375.255 269.984,375.15 271.732,374.985 273.48,374.769 275.228,374.565 276.976,374.441 278.725,374.29 280.473,373.965 282.221,373.536 
 283.969,373.13 285.717,372.745 287.465,372.274 289.213,371.667 290.962,370.965 292.71,370.151 294.458,369.24 296.206,368.325 297.954,367.356 299.702,366.139 
 301.451,364.539 303.199,362.692 304.947,360.805 306.695,358.94 308.443,357.057 310.191,354.82 311.94,352.206 313.688,349.384 315.436,346.149 317.184,342.478 
 318.932,338.517 320.68,334.361 322.428,329.892 324.177,324.882 325.925,319.774 327.673,314.53 329.421,308.659 331.169,302.125 332.917,294.965 334.666,287.253 
 336.414,279.345 338.162,271.539 339.91,263.607 341.658,255.198 343.406,246.092 345.155,236.374 346.903,226.565 348.651,216.565 350.399,205.797 352.147,194.704 
 353.895,183.583 355.643,172.172 357.392,160.975 359.14,150.513 360.888,140.215 362.636,129.199 364.384,117.966 366.132,107.297 367.881,97.2422 369.629,87.5367 
 371.377,77.6169 373.125,67.742 374.873,58.2671 376.621,49.7303 378.37,42.55 380.118,36.01 381.866,30.4423 383.614,25.4969 385.362,20.7707 387.11,16.9746 
 388.858,14.2093 390.607,12.3382 392.355,11.811 394.103,12.8728 395.851,14.6059 397.599,16.431 399.347,18.3694 401.096,21.1478 402.844,25.4198 404.592,31.0568 
 406.34,37.904 408.088,45.6065 409.836,53.1931 411.584,60.0218 413.333,67.3469 415.081,77.0511 416.829,88.6396 418.577,99.8503 420.325,109.753 422.073,119.566 
 423.822,130.201 425.57,141.29

In [29]:
[mean(bdrawst) std(bdrawst)]

1×2 Array{Float64,2}:
 2.02478  0.682791

In [38]:
vline!([quantile(bdrawst,[0.025,0.975])],linecolor=:green,label="",legend=:topleft)

<?xml version="1.0" encoding="utf-8"?>
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 -4 
 
 
 -2 
 
 
 0 
 
 
 2 
 
 
 4 
 
 
 0.1 
 
 
 0.2 
 
 
 0.3 
 
 
 0.4 
 
 
 0.5 
 
<polyline clip-path="url(#clip02)" style="stroke:#0000ff; stroke-width:1; stroke-opacity:1; fill:none" points="
 32.2221,375.813 37.3597,375.813 42.4973,375.813 47.6349,375.813 52.7725,375.813 57.91,375.813 63.0476,375.813 68.1852,375.813 73.3228,375.813 78.4604,375.813 
 83.598,375.813 88.7356,375.813 93.8732,375.813 99.0107,375.813 104.148,375.813 109.286,375.813 114.424,375.813 119.561,375.813 124.699,375.813 129.836,375.813 
 134.974,375.813 140.111,375.813 145.249,375.813 150.387,375.813 155.524,375.813 160.662,375.813 165.799,375.813 170.937,375.813 176.075,375.813 181.212,375.813 
 186.35,375.813 191.487,375.813 196.625,375.813 201.762,375.813 206.9,375.813 212.038,375.813 217.175,375.812 222.313,375.811 227.45,375.809 232.588,375.805 
 237.726,375.797 242.863,375.782 248.001,375.755 253.138,375.706 258.276,375.62 263.414,375.474 268.551,375.229 273.689,374.831 278.826,374.198 283.964,373.213 
 289.101,371.718 294.239,369.504 299.377,366.304 304.514,361.79 309.652,355.581 314.789,347.255 319.927,336.376 325.065,322.531 330.202,305.384 335.34,284.733 
 340.477,260.577 345.615,233.171 350.753,203.068 355.89,171.141 361.028,138.562 366.165,106.749 371.303,77.2764 376.44,51.7449 381.578,31.6443 386.716,18.2086 
 391.853,12.2911 396.991,14.2744 402.128,24.0298 407.266,40.931 412.404,63.9206 417.541,91.6194 422.679,122.464 427.816,154.849 432.954,187.266 438.092,218.409 
 443.229,247.253 448.367,273.084 453.504,295.502 458.642,314.387 463.779,329.848 468.917,342.162 474.055,351.71 479.192,358.923 484.33,364.234 489.467,368.046 
 494.605,370.716 499.743,372.541 504.88,373.758 510.018,374.55 515.155,375.054 520.293,375.367 525.431,375.556 530.568,375.669 535.706,375.734 540.843,375.77 
 545.981,375.791 
 "/>
<polyline clip-path="url(#clip02)" style="stroke:#ff0000; stroke-width:1; stroke-opacity:1; fill:none" points="
 214.043,375.813 215.791,375.813 217.539,375.813 219.287,375.81 221.035,375.807 222.784,375.808 224.532,375.811 226.28,375.812 228.028,375.809 229.776,375.805 
 231.524,375.8 233.272,375.79 235.021,375.783 236.769,375.787 238.517,375.792 240.265,375.792 242.013,375.791 243.761,375.783 245.51,375.765 247.258,375.752 
 249.006,375.743 250.754,375.723 252.502,375.7 254.25,375.681 255.999,375.657 257.747,375.61 259.495,375.566 261.243,375.521 262.991,375.461 264.739,375.402 
 266.487,375.333 268.236,375.255 269.984,375.15 271.732,374.985 273.48,374.769 275.228,374.565 276.976,374.441 278.725,374.29 280.473,373.965 282.221,373.536 
 283.969,373.13 285.717,372.745 287.465,372.274 289.213,371.667 290.962,370.965 292.71,370.151 294.458,369.24 296.206,368.325 297.954,367.356 299.702,366.139 
 301.451,364.539 303.199,362.692 304.947,360.805 306.695,358.94 308.443,357.057 310.191,354.82 311.94,352.206 313.688,349.384 315.436,346.149 317.184,342.478 
 318.932,338.517 320.68,334.361 322.428,329.892 324.177,324.882 325.925,319.774 327.673,314.53 329.421,308.659 331.169,302.125 332.917,294.965 334.666,287.253 
 336.414,279.345 338.162,271.539 339.91,263.607 341.658,255.198 343.406,246.092 345.155,236.374 346.903,226.565 348.651,216.565 350.399,205.797 352.147,194.704 
 353.895,183.583 355.643,172.172 357.392,160.975 359.14,150.513 360.888,140.215 362.636,129.199 364.384,117.966 366.132,107.297 367.881,97.2422 369.629,87.5367 
 371.377,77.6169 373.125,67.742 374.873,58.2671 376.621,49.7303 378.37,42.55 380.118,36.01 381.866,30.4423 383.614,25.4969 385.362,20.7707 387.11,16.9746 
 388.858,14.2093 390.607,12.3382 392.355,11.811 394.103,12.8728 395.851,14.6059 397.599,16.431 399.347,18.3694 401.096,21.1478 402.844,25.4198 404.592,31.0568 
 406.34,37.904 408.088,45.6065 409.836,53.1931 411.584,60.0218 413.333,67.3469 415.081,77.0511 416.829,88.6396 418.577,99.8503 420.325,109.753 422.073,119.566 
 423.822,130.201 425.57,141.29

In [39]:
quantile(bdrawst,[0.025,0.975])

2-element Array{Float64,1}:
 0.685958
 3.36428 